Add Echo Service
jiks-dev/jiks-net-game-server pull request #1
Opened 2022-03-05 19:37 UTC by rd-dhyoo

# Description
- String을 서로 주고 받을 수 있도록 서버 개설

2022-03-08 02:34 UTC, karriz-dev requested changes

2022-03-08 02:34 UTC, karriz-dev commented on jiksGame.Chat.Client/AsynchronousSocketClient.cs
> +        public StringBuilder sb = new StringBuilder();
sb 라는 명칭보다는 `receivedDataBuilder` 나 `receivedDataStringBuilder` 같은 확실한 명칭을 확인해주시면 좋을 것 같습니다.

2022-03-08 02:34 UTC, karriz-dev commented on src/JiksGame.Core/Engines/SocketEngine.cs
> +            await Task.Delay(20);
소켓 서버에서 Task를 실행할 때에는 delay가 존재하면 처리 속도가 느려지기 때문에 삭제를 해야할 것 같습니다.

2022-03-08 02:34 UTC, karriz-dev commented on src/JiksGame.Core/Managers/Sockets/SocketManager.cs
> +            var localEndPoint = new IPEndPoint(ipAddress, 11000);
서버의 port는 client와 동일하게 const 처리를 해주면 좋을 것 같습니다

2022-03-08 02:34 UTC, karriz-dev commented on src/JiksGame.Core/Managers/Sockets/SocketManager.cs
> +            uint uniqueId = 1;
UniqueID인데 1로 고정으로 되어있는데 추후 수정할 부분인가요 ? 
고정된다면 `SendAsync` 함수 부분에 이슈가 있을 것 같습니다.

2022-03-08 02:34 UTC, karriz-dev commented on src/JiksGame.Core/readme.txt
> +- 이 프로젝트는 Nurget 파일을 생성합니다.
nuget ? nugget ? nurget이 오타가 아닌지 확인 바랍니다.

2022-03-08 02:34 UTC, karriz-dev commented
다른 직스원 분들이 알아보기 쉽게 간단한 전체 아키텍처 그림을 추가 해주시면 더 좋을 것 같습니다 👍

2022-03-08 02:36 UTC, rd-dhyoo commented on src/JiksGame.Core/readme.txt
> +- 이 프로젝트는 Nurget 파일을 생성합니다.
오타입니다

2022-03-08 02:36 UTC, MarkYoo23 commented on src/JiksGame.Core/Managers/Sockets/SocketManager.cs
> +            uint uniqueId = 1;
네 맞습니다. 고치려고 했었는데 수정 해서 올리겠습니다~

2022-03-08 02:37 UTC, rd-dhyoo commented on src/JiksGame.Core/Managers/Sockets/SocketManager.cs
> +            var localEndPoint = new IPEndPoint(ipAddress, 11000);
이 부분은 System Configuration Entity 에서 가져 오는 방향으로 개발 하려고 합니다.

2022-03-08 02:38 UTC, rd-dhyoo commented on src/JiksGame.Core/Engines/SocketEngine.cs
> +            await Task.Delay(20);
등록된 Background Service가 2개 동작 하고 있기 때문에, Net Core의 구조상 Delay가 없으면 둘다 동작 할 수 있는지 확인이 필요 할 것 같습니다.

2022-03-08 02:39 UTC, MarkYoo23 commented on jiksGame.Chat.Client/AsynchronousSocketClient.cs
> +        public StringBuilder sb = new StringBuilder();
클라이언트는 다른 PR에 테스트 코드가 아닌, 어떤 기능을 할 지 설계 후 업데이트 하겠습니다!

2022-03-08 04:24 UTC, rd-dhyoo commented
> 다른 직스원 분들이 알아보기 쉽게 간단한 전체 아키텍처 그림을 추가 해주시면 더 좋을 것 같습니다 👍

네 아키텍처 관련해서는 저녁에 그러서 올리겠습니다~

2022-03-08 12:13 UTC, rd-dhyoo commented on src/JiksGame.Core/Engines/SocketEngine.cs
> +            await Task.Delay(20);
Delay가 없으면 둘 다 동작 할 수 없습니다.

2022-03-18 08:53 UTC, karriz-dev commented on src/JiksGame.Core/Engines/SocketEngine.cs
> +            await Task.Delay(20);
혹시 해당 내용을 확인해볼 수 있는 reference가 있을까요 ?

2022-03-18 08:54 UTC, karriz-dev approved these changes
LGTM

2022-05-01 05:25 UTC, merged